# Makefile for the include files

deps-y += include/unknown/platform.h
deps-y += include/unknown/print_format.h
deps-y += include/unknown/lexer.h
deps-y += include/unknown/types.h
deps-y += include/unknown/list.h
