# Makefile for the include files

deps-y += include/unknown/platform.h
deps-y += include/unknown/print_format.h
deps-y += include/unknown/tokenizer.h
deps-y += include/unknown/types.h
deps-y += include/unknown/list.h
